/*
 * Dynamicdns.pro
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using dynamicdns.api.Client;
using dynamicdns.api.Api;
// uncomment below to import models
//using dynamicdns.api.Model;

namespace dynamicdns.api.Test.Api
{
    /// <summary>
    ///  Class for testing SubdomainApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SubdomainApiTests : IDisposable
    {
        public SubdomainApiTests()
        {
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubdomainApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SubdomainApi
            //Assert.IsType<SubdomainApi>(instance);
        }

        /// <summary>
        /// Test Updateip
        /// </summary>
        [Fact]
        public void UpdateipTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string subdomain = null;
            //Object? body = null;
            //var response = instance.Updateip(subdomain, body);
            //Assert.IsType<Updateip200Response>(response);
        }
    }
}
