/*
 * Dynamicdns.pro
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using dynamicdns.api.Model;
using dynamicdns.api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace dynamicdns.api.Test.Model
{
    /// <summary>
    ///  Class for testing Deleteip200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Deleteip200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Deleteip200Response
        //private Deleteip200Response instance;

        public Deleteip200ResponseTests()
        {
            // TODO uncomment below to create an instance of Deleteip200Response
            //instance = new Deleteip200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Deleteip200Response
        /// </summary>
        [Fact]
        public void Deleteip200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" Deleteip200Response
            //Assert.IsType<Deleteip200Response>(instance);
        }
    }
}
