/*
 * Dynamicdns.pro
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using dynamicdns.api.Model;
using dynamicdns.api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace dynamicdns.api.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateRequest
        //private UpdateRequest instance;

        public UpdateRequestTests()
        {
            // TODO uncomment below to create an instance of UpdateRequest
            //instance = new UpdateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateRequest
        /// </summary>
        [Fact]
        public void UpdateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateRequest
            //Assert.IsType<UpdateRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
    }
}
