/*
 * Dynamicdns.pro
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using dynamicdns.api.Model;
using dynamicdns.api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace dynamicdns.api.Test.Model
{
    /// <summary>
    ///  Class for testing Updateip200ResponseAnyOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Updateip200ResponseAnyOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Updateip200ResponseAnyOf
        //private Updateip200ResponseAnyOf instance;

        public Updateip200ResponseAnyOfTests()
        {
            // TODO uncomment below to create an instance of Updateip200ResponseAnyOf
            //instance = new Updateip200ResponseAnyOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Updateip200ResponseAnyOf
        /// </summary>
        [Fact]
        public void Updateip200ResponseAnyOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" Updateip200ResponseAnyOf
            //Assert.IsType<Updateip200ResponseAnyOf>(instance);
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
