/*
 * Dynamicdns.pro
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using dynamicdns.api.Model;
using dynamicdns.api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace dynamicdns.api.Test.Model
{
    /// <summary>
    ///  Class for testing Update400Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Update400ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Update400Response
        //private Update400Response instance;

        public Update400ResponseTests()
        {
            // TODO uncomment below to create an instance of Update400Response
            //instance = new Update400Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Update400Response
        /// </summary>
        [Fact]
        public void Update400ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" Update400Response
            //Assert.IsType<Update400Response>(instance);
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
